# Generated by Django 3.2.15 on 2022-09-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='acao_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='acao_principal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
